---
# tasks file for ansible-role-linuxbrew
- name: "Linuxbrew | check if {{ lb__brew }} exists."
  ansible.builtin.stat:
    path: "{{ lb__brew }}"
  register: "lb__brew_stat"

# Todo: maybe check if brew has been *sourced* too using command -v brew.

- name: "Linuxbrew | install Linuxbrew."
  ansible.builtin.include_tasks: "tasks/install.yml"
  when: "not lb__brew_stat.stat.exists"

- name: "Linuxbrew | configure shell for Linuxbrew use."
  ansible.builtin.include_tasks: "tasks/shell.yml"
  when: "not lb__brew_stat.stat.exists"
