---
# Main supervisory Linuxbrew configuration tasks.
- name: "Linuxbrew | check if {{ lb__brew }} exists."
  ansible.builtin.stat:
    path: "{{ lb__brew }}"
  register: "lb__brew_stat"

- name: "Linuxbrew | install Linuxbrew."
  ansible.builtin.include_tasks: "tasks/install.yml"
  when: "not lb__brew_stat.stat.exists"

- name: "Linuxbrew | update brew and install packages."
  ansible.builtin.include_tasks: "tasks/packages.yml"
  when: >
    lb__packages|length
    or lb__update_homebrew_when_installing_packages
    or lb__update_all_when_installing_packages

- name: "Linuxbrew | configure shell for Linuxbrew."
  ansible.builtin.include_tasks: "{{ task_include }}"
  loop: "{{ lb__shell_configuration_tasks }}"
  loop_control:
    loop_var: "task_include"
