---
# Brew, package, and tap install and upgrade tasks.
- name: "Linuxbrew | update homebrew."
  community.general.homebrew:
    update_homebrew: "{{ lb__update_homebrew_when_installing_packages }}"
  become: true
  become_user: "{{ lb__owner }}"

- name: "Linuxbrew | update homebrew packages."
  community.general.homebrew:
    upgrade_all: "{{ lb__upgrade_all_when_installing_packages }}"
  become: true
  become_user: "{{ lb__owner }}"

- name: "Linuxbrew | install homebrew packages."
  community.general.homebrew:
    name: "{{ package.name }}"
    state: "{{ package.stat|default('present') }}"
    path: "{{ package.path|default(omit) }}"
    install_options: "{{ package.install_options|default(omit) }}"
  become: true
  become_user: "{{ lb__owner }}"
  loop: "{{ lb__packages }}"
  loop_control:
    loop_var: "package"

- name: "Linuxbrew | install homebrew taps."
  community.general.homebrew_tap:
    name: "{{ tap.name }}"
    state: "{{ tap.stat|default('present') }}"
    path: "{{ tap.path|default(omit) }}"
    url: "{{ tap.url|default(omit) }}"
  become: true
  become_user: "{{ lb__owner }}"
  loop: "{{ lb__taps }}"
  loop_control:
    loop_var: "tap"
