---
- name: "Linuxbrew | update homebrew"
  community.general.homebrew:
    update_homebrew: "{{ lb__update_homebrew_when_installing_packages }}"
    upgrade_all: "{{ lb__update_all_when_installing_packages }}"
  become: true
  become_user: "{{ lb__owner }}"

- name: "Linuxbrew | install package '{{ package.name }}'."
  community.general.homebrew:
    name: "{{ package.name }}"
    state: "{{ package.stat|default('present') }}"
    path: "{{ package.path|default(omit) }}"
    install_options: "{{ package.install_options|default(omit) }}"
  become: true
  become_user: "{{ lb__owner }}"
  loop: "{{ lb__packages }}"
  loop_control:
    loop_var: "package"
